export const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1559555943000,
      duration: 10800000,
      id: '261997882',
      name: 'AWS UG July Event',
      rsvp_limit: 180,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1562776200000,
      local_date: '2019-07-10',
      local_time: '18:30',
      updated: 1561712484000,
      utc_offset: 7200000,
      waitlist_count: 47,
      yes_rsvp_count: 180,
      venue: {
        id: 26431070,
        name: 'Cloudreach GmbH',
        lat: 48.143680572509766,
        lon: 11.502440452575684,
        repinned: true,
        address_1: 'Landsberger Str. 300',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1400514197000,
        name: 'Munich AWS User Group',
        id: 14546712,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'AWS-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/AWS-Munich/events/261997882/',
      description: '<p>It is our last meetup before summer break and I\'m so glad we really changed location every month until now for this year!</p> <p>This time Cloudreach (<a href="https://www.cloudreach.com/" class="linkified">https://www.cloudreach.com/</a>) is our sponsor and kind enough to provide food, drinks and a few amazing talks!</p> <p>AGENDA:<br/>18:30 - Doors open, networking, drinks, food</p> <p>19:00 - Markus (Team Internet AG) - Recent AWS announcements</p> <p>19:30 - Cloudreach - Scaling Out AWS Config<br/>Is AWS Config the answer for your Security Compliance?<br/>How to detect the unexpected and audit your teams resource usage in a multi account setup.<br/>From August on there will be a new pricing model for AWS Config, what does it mean &amp; what will be changed in upcoming new pricing model.</p> <p>20:00 - Cloudreach - Now that is built, how do you run it?<br/>First hand experience from our operations team working with AWS.<br/>What challenges they have encountered and how to overcome them, as part of organisations who\'s applications are Cloud based.</p> <p>20:30 - Cloudreach - Serverless Chrome for Work and Fun<br/>Headless Chrome brings a lot of possibilities for functional and UI application testing, as well as for various other automation tasks. But can we save some money and run it in AWS Lambda? How it all works together? What languages you can use?</p> <p>20:45 - More drinks, more networking</p> <p>If you have an office or coworking space where we can meet [masked] people), want to sponsor drinks/food or have a (lightning) talk you want to present - please let us know!</p> ',
      visibility: 'public',
    },
    {
      created: 1561033244000,
      duration: 7200000,
      id: '262475607',
      name: 'Massive Parallel and Elastic AI Pipelines with TensorFlow and Kubernetes',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1562859000000,
      local_date: '2019-07-11',
      local_time: '17:30',
      updated: 1562134663000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 115,
      group: {
        created: 1400181332000,
        name: 'Big Data Developers in Munich',
        id: 14476282,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Big-Data-Developers-in-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/262475607/',
      description: '<p>Agenda:</p> <p>17:30 Welcome and Pizza<br/>18:00 What\'s new in TensorFlow 2.0<br/>18:30 Build Enterprise AI Pipelines using KubeFlow</p> <p>Meetup taking part with our friends from PyData, please take a look, they have very interesting talks as well</p> <p><a href="https://www.meetup.com/PyData-Munchen/events/262530441" class="linkified">https://www.meetup.com/PyData-Munchen/events/262530441</a></p> ',
      visibility: 'public',
      pro_is_email_shared: false,
    },
    {
      created: 1561302363000,
      duration: 7200000,
      id: '262555199',
      name: 'DDD - Lessons Learned',
      rsvp_limit: 150,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1562691600000,
      local_date: '2019-07-09',
      local_time: '19:00',
      updated: 1561302363000,
      utc_offset: 7200000,
      waitlist_count: 57,
      yes_rsvp_count: 150,
      venue: {
        id: 26052903,
        name: 'Rohde & Schwarz GmbH & Co. KG',
        lat: 48.127593994140625,
        lon: 11.612282752990723,
        repinned: false,
        address_1: 'Mühldorfstraße 15',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1399578043000,
        name: 'Microservices Meetup Munich',
        id: 14341692,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Microservices-Meetup-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Microservices-Meetup-Munich/events/262555199/',
      description: '<p>Please keep your RSVP up to date, free spots are always in demand!</p> <p>We will meet at 6.30pm at Rohde &amp; Schwarz Technology Center with pizza and drinks.</p> <p>The talk starts at 7pm and will be in English.</p> <p>Dr. Baris Guezelarslan: DDD - Lessons Learned</p> <p>After the talk we have time for drinks and conversations.</p> <p>Abstract:<br/>This talk describes the speaker\'s path from a monolith towards a service-based application. It is a potpourri of all the light bulb moments on this journey including actor models, event sourcing, CQRS, functional programming, polyglot persistence, and workflow engines.</p> <p>This talk will cover the problem domain, which is an enterprise application processing data streams from different sensors (IoTs), without going into too much detail. Due to performance issues, the content will be based on event sourcing and CQRS which is often considered too complex (for no reason). It will be shown that the basic idea and the implementation can be very simple. The split of the write and the read model will also help to separate behavior from data. The main focus will not be based on technical implementations, but on how to change your mindset to solve your problem.</p> <p>Bio:<br/>Baris is currently working in the Innovation Lab at Rohde &amp; Schwarz. Previously, he was responsible for a high-throughput backend. He is a DDD thinker and tinker. He still feels like an apprentice on DDD and continues to learn more on this topic. Accordingly, he is looking forward to discuss his experiences with you in order to get constructive feedback.</p> <p>Location:<br/>Entrance is at the gate of Rohde &amp; Schwarz at Mühldorfstr. 15 (at the pedestrian crossing). From there we will bring you to the Rohde &amp; Schwarz Technology Center.</p> ',
      visibility: 'public',
    },
    {
      created: 1548927356000,
      duration: 10800000,
      id: '258555146',
      name: 'Design Thinking Method Jam',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1562776200000,
      local_date: '2019-07-10',
      local_time: '18:30',
      updated: 1561739161000,
      utc_offset: 7200000,
      waitlist_count: 8,
      yes_rsvp_count: 56,
      venue: {
        id: 26483775,
        name: 'Celonis SE',
        lat: 48.147335052490234,
        lon: 11.578679084777832,
        repinned: true,
        address_1: 'Theresienstraße 6',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1460553553000,
        name: 'Design Thinking München',
        id: 19836170,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'DT-Muc',
        who: 'Design Thinkers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/DT-Muc/events/258555146/',
      description: '<p>DESIGN THINKING METHOD JAM</p> <p>Wir alle arbeiten gern mit Design Thinking Methoden, die wir gut kennen und schon oft gemacht haben. Oder wir wandeln Methoden um oder ab, weil sie so besser oder für einen anderen Zweck funktionieren. Bei diesem Meet-Up geht es darum, über den eigenen Methoden-Tellerrand zu schauen und neue Methoden kennenzulernen und auszuprobieren.<br/>Der Method Jam ist ein bewährtes Format an der HPI School of Design Thinking, um den Methodenaustausch und Weiterentwicklung unter den Coaches zu institutionalisieren und voneinander zu lernen. Außerdem bietet er die Möglichkeit, neue Methoden risikofrei und mit viel Spaß auszuprobieren und Feedback zu sammeln.</p> <p>Alle Teilnehmer*innen werden gebeten eine Methode mitzubringen/vorzubereiten, die sie in 30 Minuten mit einem Team von 5-7 Personen vorstellen, ausprobieren und reflektieren können.<br/>Jede*r Teilnehmer*in hat die Möglichkeit, seine/ihre Methode zu Beginn in einer Minute vorzustellen. Danach wählen die Teilnehmer*innen aus, welche 4-5 Methoden dann in Kleingruppen ausprobiert werden sollen. In einer zweiten Runde werden weitere Methoden ausprobiert, so dass auch die Moderator*innen der ersten Runde Gelegenheit haben, eine neue Methode zu erlernen. Im Anschluss werden im Plenum alle Methoden kurz präsentiert und reflektiert.</p> <p>Dieses Meet-Up benötigt etwas Vorbereitung. Bitte bringt eine Methode mit und macht Euch vorab Gedanken über folgende Fragen:</p> <p>- Titel der Methode<br/>- Ziel und Zielgruppe<br/>- Wo im DT-Prozess wird sie angewendet? (Warm-Up, Ideation, Transfer, etc.)<br/>- Kurze Skizze wie es funktioniert<br/>- AHA-Moment/ warum ist sie so toll?</p> <p>Wichtig ist es, die Methode nicht nur vorzustellen, sondern sie gemeinsam mit den anderen Teilnehmer*innen auszuprobieren. Post-Its, Papier und Stifte stellen wir zur Verfügung, anderes Material und Templates bitte mitbringen falls notwendig.</p> <p>AGENDA:</p> <p>18:30: Ankommen &amp; Kennenlernen, Methoden-Pitch vorbereiten<br/>19:00: Methoden-Pitches &amp; Voting (1min/ Methode)<br/>19:45: Method Jamming (2 Runden à 4-5 Methoden in Kleingruppen parallel)<br/>21:00: Method Gallery (Vorstellung aller Methoden im Plenum)<br/>21:30: Ende</p> <p>Wir freuen uns riesig, Jule Schröder als Co-Organisatorin bei diesem Meetup dabei zu haben!</p> <p>Jule Schröder hat 2013/14 den Basic und Advanced Track an der HPI School of Design Thinking in Potsdam absolviert und im Anschluss als Innovations- und Design Thinking Coach bei Kill Your Darling und and der HPI Academy GmbH in unzähligen Workshops Design Thinking als Methode unterrichtet sowie Innovationsprozesse moderiert und begleitet. Mit ihrem Integrationsprojekt „Kitchen on the Run“ gewann sie 2015 die Advocate Europe Idea Challenge. Seit 2018 begleitet sie selbstständig Innovationsprojekte vor allem in der Pharma-Industrie und im Kulturbereich.</p> ',
      visibility: 'public',
    }

  ],
}

